language: python
sudo: false
group: travis_latest
language: python
jobs:
    include:
      - python: 2.7    # 2.7.14 pip  9.0.1
      - python: 3.6    # 3.6.3  pip  9.0.1
      - python: 3.7    # 3.7.0  pip 10.0.1
        dist: xenial
        sudo: true
      - python: pypy   # 2.7.13 pip  9.0.1
      - python: pypy3  # 3.5.3  pip  9.0.1
env:
    global:
        - PYTHONHASHSEED=random
        - PIP_UPGRADE_STRATEGY=eager
script:
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"


cache:
  pip: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
